Fix usage
Usage & package names don't match, so the usage instructions are wrong.

```
$ PYTHONPATH=. python -c'from pybloom import BloomdClient'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named pybloom

$ PYTHONPATH=. python -c'from pybloomd.pybloomd import BloomdClient'
$
```